### ISSUE TITLE
How to deploy a gremlin server with Unipop-elastic2?

### ISSUE THREAD

**Issue by jiangyifangh** [sirensolutions/unipop#7]
Great works!
I am currently working on a project that require letting gremlin talk with elasticsearch. However, the original repository hasn't fully developed unipop-elastic2 yet. It seems that unipop-elastic2 has been developed here. Could you give any advice about how to set up a gremlin server using unipop-elastic2?

Thanks a lot!

**Comment by jccq** [comment]
Hi Tony, we support this via the Kibi Enterprise Edition project (http://siren.solutions/kibi and http://siren.solutions/kibi/enterprise) - just a small part of the code sits here. Would you be able to contact us at info@siren.solutions and we could start a conversation there. Best.
